config/routes.rb
Rails.application.routes.draw do
  get 'webhooks/webhook'
  root 'pages#home'
  get :search, to: "search#index"
  devise_for :users
  resources :contact_forms, only: [:create]
 
  resources :portfolios, except: :new do
    member do
      resources :payments, only: [:index, :create]
    end
    resources :tags, only: [:create, :destroy], param: :tag_id, controller: :portfolio_tags
    resources :blocks, only: [:index, :create, :destroy] do
      resources :additional_informations, only: [:index, :update]
      patch :positions, on: :collection, to: "block_positions#update"
    end
    resources :profiles, only: [:index, :update]
    resources :experiences, only: [:index, :create, :destroy]
    resources :educations, only: [:index, :create, :destroy]
    resources :skills, only: [:index, :create, :destroy]
    resources :hobbies, only: [:index, :create, :destroy]
    resources :languages, only: [:index, :create, :destroy]
    resources :abouts, only: [:index, :update]
    resources :socials, only: [:index, :create, :destroy]
    resources :abouts, only: [:index, :update]
  end
 
  resources :tags, only: :index
  get '/:slug', to: 'portfolios#show'

  post '/webhooks', to: 'webhooks#webhooks'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  MAX_NUMBER_OF_TAGS = 4
  paginates_per 5
 
  before_validation :set_slug, on: :create
 
  belongs_to :user
 
  has_one :profile, :dependent => :destroy
  has_one :about, :dependent => :destroy
  has_one :order
 
  has_many :blocks, :dependent => :destroy
  has_many :portfolio_tags, :dependent => :destroy
  has_many :tags, through: :portfolio_tags
  has_many :educations, :dependent => :destroy
  has_many :experiences, :dependent => :destroy
  has_many :hobbies, :dependent => :destroy
  has_many :skills, :dependent => :destroy
  has_many :languages, :dependent => :destroy
  has_many :socials, :dependent => :destroy
  has_one :contact, :dependent => :destroy
  has_many :additional_informations, :dependent => :destroy
 
  validates :slug, presence: true, uniqueness: true
  validates :tags, length: { in: 0..MAX_NUMBER_OF_TAGS, message: "can't have more than #{MAX_NUMBER_OF_TAGS} tags" }
 
 
  enum temp_avatar: { blue_robot: 0, green_robot: 1, orange_red_robot: 2, purple_robot: 3, red_robot: 4, yellow_robot: 5 }
 
 
  before_create :set_random_temp_avatar
 
 
  private
 
 
  def set_random_temp_avatar
    avatars_list = Portfolio.temp_avatars.keys
    self.temp_avatar = avatars_list.sample
  end
 
  def set_slug
    if self.slug.nil?
      slug_generator = PortfolioSlugGeneratorService.new
      self.slug = slug_generator.call
    end
  end
 
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :load_portfolios, only: :index
  before_action :load_portfolio, only: [:edit, :update]
  skip_before_action :authenticate_user!, only: :show
 
 
  def index
    authorize(Portfolio)
  end
 
 
  def create
    build_portfolio
    authorize @portfolio
    @portfolio.save
    redirect_to edit_portfolio_path(@portfolio)
  end
 
 
  def show
    respond_to do |format|
      format.json { 
        @portfolio = Portfolio.find(params[:id])
        authorize @portfolio
        render json: { portfolio: @portfolio }, include: { tags: { only: [:id, :title] } }, status: :ok
      }
      format.html {
        @portfolio = Portfolio.find_by!(slug: params[:slug])
 
        unless @portfolio.active || @portfolio.user == current_user
          raise ActiveRecord::RecordNotFound
        end
        
        authorize @portfolio
      }
    end
  end
 
 
  def edit
    authorize @portfolio
  end
 
 
  def update
    build_portfolio
    authorize @portfolio
    save_and_render
  end
 
 
  private
 
 
  def save_and_render
    if @portfolio.save
      head :ok
    else
      render json: { errors: @portfolio.errors.full_messages, portfolio: @portfolio.reload }, status: :unprocessable_entity
    end
  end
 
 
  def build_portfolio
    @portfolio ||= portfolio_scope.build
    @portfolio.attributes = portfolio_params
  end
 
 
  def portfolio_params
    return {} unless params.has_key?(:portfolio)
    params.require(:portfolio).permit(:slug, :listed, :active, :remote_ok)
  end
 
 
  def load_portfolio
    @portfolio = portfolio_scope.find(params[:id])
  end
 
 
  def load_portfolios
    @portfolios = portfolio_scope.all
  end
 
 
  def portfolio_scope
    policy_scope(Portfolio)
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
 
  def render_block(block)
    render partial: "portfolios/shared/#{block.kind}_widget.html.erb", locals: {portfolio: block.portfolio}
  end
 
  def render_profile_photo(portfolio)
    if portfolio.profile.present? && portfolio.profile.photo.attached?
      image_url = url_for(portfolio.profile.photo.variant(resize: "150x150"))
    end
    image_url ||= "avatars/#{portfolio.temp_avatar}"
    image_tag image_url,  class: 'responsive-img'
  end
 
 
  def render_profile_name(portfolio)
    return portfolio.profile.name if portfolio.profile.present?
    "Ainda não preenchido"
  end
 
 
  def render_profile_title(portfolio)
    return portfolio.profile.title if portfolio.profile.present?
    "Ainda não preenchido"
  end
 
 
  def render_portfolio_tags(tags)
    disabled_tags_quant = Portfolio::MAX_NUMBER_OF_TAGS - tags.count
    tags.each { |tag| concat draw_tag(tag.title) }
    disabled_tags_quant.times { concat draw_tag(unused_label, color: "grey") }
  end
 
 
  private
 
 
  def unused_label
    content_tag :i, "Vázia"
  end
 
 
  def draw_tag(title, color: "blue-grey")
    content_tag :div, class: "col s12 m6 l6" do
      concat content_tag :span, title, class: "label #{color} #{color}-darken-5 #{color}-text text-lighten-4"
    end
  end
end

app/views/portfolios/_portfolio.html.erb
<div class="portfolio col s12 m4 l4">
  <div class="card-panel center">
    <div class="col s12 m12 l12">
      <a href="" class="remove-portfolio right custom-grey-text text-darken-2">
        <i class="fa fa-icon fa-times"></i>
      </a>
    </div>
    <div class="row"><%= render_profile_photo(portfolio) %></div>
    <span class="name grey-text text-darken-2"><%= render_profile_name(portfolio) %></span>
    <div class="label grey darken-3 grey-text text-lighten-2"><%= render_profile_title(portfolio) %></div>
    <div class="row tags">
      <% render_portfolio_tags(portfolio.tags) %>
    </div>
    <div class="row">
      <div class="col s6 m6 l6">
        <%= link_to "Editar", edit_portfolio_path(portfolio), class: "btn light-blue lighten-2 col m12 s12" %>
      </div>
      <div class="col s6 m6 l6">
        <%= link_to "Visualizar", "/#{portfolio.slug}", class: "btn orange darken-1 right col m12 s12" %>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<div id="portfolio-edit" data-portfolio="<%= @portfolio.id %>"></div>

app/views/portfolios/index.html.erb
<div class="row portfolios">
  <div class="col m12">
    <p class="custom-grey-text title">Seus Portfólios</p>
  </div>
  
  <%= render @portfolios %>
</div>

<div class="add-portfolio col s12 m3 l3">
    <div class="card-panel center">
        <%= link_to portfolios_path, method: :post, class: "new-portfolio" do %>
        	<%= image_tag("add_portfolio.png", width: "150px") %>
        <% end %>
    </div>
</div>

app/views/portfolios/show.html.erb
<div class="row widgets">
  <div class="col m3 offset-m1 blocks portfolio_left s12">
    <% @portfolio.blocks.where(side: :left).order(:position).each do |block| %>
      <%= render_block(block) %>
    <% end %>
  </div>
 
  <div class="col m7 widget_right blocks s12">
    <% @portfolio.blocks.where(side: :right).order(:position).each do |block| %>
      <%= render_block(block) %>
    <% end %>
  </div>
</div>